
server:
  port: 8099
  servlet:
    context-path: /wx_shop
  ssl:
    key-store: classpath:m.szmlkq.com.pfx
    key-store-password: BV035j0t
    key-store-type: PKCS12
spring:
  application:
    name: service-shop
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.107.47.13:3306/wx_shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: MylikeKq@88
    #      url: jdbc:mysql://120.79.78.188:3306/wx_shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #      username: root
    #      password: 0ecgKHrq
    #      url: jdbc:mysql://172.16.19.106:3306/wx_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #      username: root
    #      password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.47.13:8761/eureka/
mybatis:
  type-aliases-package: com.wx_shop.serviceshop.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.wx_shop.serviceshop.dao: debug
myapp:
  redisWxUserAccessToken: "user.wxUserAccessToken"
  redisWxUserRefreshToken: "user.wxUserRefreshToken"
  redisWxAccessToken: "sys.wxAccessToken"
  redisWxRefreshToken: "sys.wxRefreshToken"
jedis :
  pool :
    host : 172.16.19.101
    port : 6379
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000
