eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.47.13:8761/eureka/


spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: http://172.16.19.106:7070/chenkaiming/wx_shop_cloud
          username: chenkaiming
          password: 112113ming
 #####################################################################################################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.19.106:3306/wx_shop
    name: root
    password: root
#####################################################################################################
server:
  port: 8087