server:
  port: 8077
  servlet:
    context-path: /rabbit

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.107.47.13:8761/eureka/


spring:

  application:
    name: rabbitmq_test
  redis:
    database: 0
    host: 47.107.47.13
    port: 6379
    password:
    jedis:
      pool:
        max-wait: 10000
        max-active: 1024
        max-idle: 200
        min-idle: 0
    timeout: 10000
  rabbitmq:
    host: 47.107.47.13
    port: 5672
    username: admin
    password: admin
    virtual-host: /ad-Vhost
    listener:
      simple:
#        auto-startup: true
#        default-requeue-rejected: true
        acknowledge-mode: manual
#        /为信道中最大消息并行数量
        prefetch: 10
#    template:
#      retry:
#        enabled: true
#        initial-interval: 1000
#        max-attempts: 3
#        max-interval: 10000
#        multiplier: 1.0

